name: deploy to lambda
on: [push]
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest  #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
    #Using versioned actions 
      - uses: actions/checkout@v2  # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:  
          node-version: '14' #--> Specify the Version of the Node 
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
        # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy
      #   env:
      #     CI: true
      #   run: |
      #     npm i 
      # - name: deploy
      #   run: |
      #     zip -j deploy.zip ./* #--> Zip the Code As we know lambda function accept the zip file.
      #     aws lambda update-function-code --function-name=test --zip-file=fileb://deploy.zip 
      # - name: serverless deploy
      #     uses: serverless/github-action@v3.1
      #     with:
      #       args: deploy