name: deploy to lambda
on: [push]
jobs:
  deploy_lambda:
    runs-on: ubuntu-latest  #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
    #Using versioned actions 
      - uses: actions/checkout@v2  # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:  
          node-version: '14' #--> Specify the Version of the Node 
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
        # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: npm install
        env:
          CI: true
        run: |
          npm ci 
      - name: deploy
        run: |
          zip -j deploy.zip ./* #--> Zip the Code As we know lambda function accept the zip file.
          aws lambda update-function-code --function-name=test --zip-file=fileb://deploy.zip 
# At last the AWS CLI command to Update the Zip file with existing One (With Correct Function Name)
  # deploy_source:
  #   name: deploy lambda from source
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout source code
  #       uses: actions/checkout@v3
  #     - name: default deploy
  #       if: github.ref == 'refs/heads/develop'
  #       uses: appleboy/lambda-action@v0.1.9
  #       with:
  #         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws_region: ${{ secrets.AWS_REGION }}
  #         function_name: test
  #         source: handler/app.js
